version: '3'

services:
  react-app:
    image: react-app
    # build: .
    stdin_open: true
    ports:
      - '3000:3000'
    # volumes:
    #   - ./src:/app/src
    networks:
      - mern-app
    # environment:
    #   - REACT_APP_NAME=git-search
    #   - CHOKIDAR_USEPOLLING=true
  api-server:
    image: api-server
    ports:
      - '5000:5000'
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
